apiVersion: v1
kind: BuildConfig
metadata:
  creationTimestamp: 2017-02-08T03:53:19Z
  name: jmeter-test-suite
spec:
  output:
    to:
      kind: ImageStreamTag
      name: jmeter-test-suite:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      ref: master
      uri: https://github.com/rajeshd2090/openshift-jmeter
    type: Git
    contextDir: /
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: rhel7-jmeter3:latest
        namespace: jmeter
    type: Docker
